### ISSUE TITLE
About RIMES dataset.

### ISSUE THREAD

**Issue by lxq0204** [tobiasvanderwerff/MetaHTR#1]
Thank you very much for the code. The RIMES has been used  in your paper, but now the link of the RIMES is no longer valid. Could you share this dataset?  I promise to use it only for academic research.

**Comment by tobiasvanderwerff** [comment]
Hi,

I do not currently have access to the RIMES dataset -- I suggest you contact the RIMES authors directly if you want access. Also, this is an unofficial implementation of MetaHTR, i.e. I am not one of the authors of the paper.

Tobias
